# This script reads files containing extended information of memory and CPU usages of minimal apps and generates a CSV file containing the most useful information about memory and CPU usages for several runs.
# Note that the files the script reads are generated by the Python script collectNetworkMemoryAndCPU.py.

require(data.table)
require(doBy)
require(tictoc)

SDK_TYPE = "CrashReporting"
DATA_FOLDER = paste("/Experiments/", SDK_TYPE, "/data/", sep="")
OUTPUT_PATH = paste("/Experiments/", SDK_TYPE, "/results/", sep="")

dataByRun <- data.table("SdkName"=character(),
                        "SdkType"=character(),
                         "Run"=numeric(),
                         "Metric"=character(),
                         "MinValue"=numeric(),
                         "AvgValue"=numeric(),
                         "MedValue"=numeric(),
                         "MaxValue"=numeric(),
                         stringsAsFactors=FALSE)

####################################################
# Reading of files containing info about CPU usage #
####################################################
file.names <- dir(DATA_FOLDER, pattern ="*.top")
for(fileIndex in 1:length(file.names))
{
  elements = unlist(strsplit(file.names[fileIndex],"-"))
  sdk = elements[1]
  run = unlist(strsplit(elements[2],".top"))
  
  tic(msg = "File read!")
  print(paste("-> Reading file '", file.names[fileIndex], "'", sep=""))
  filePath = paste(DATA_FOLDER,file.names[fileIndex], sep="")
  dataRead=fread(filePath, header = F, sep = ' ',select = c("V3"), col.names = c("CPU"))
  dataRead$CPU = as.numeric(gsub("%", "", dataRead$CPU))
  toc()
  
  row = list(as.character(sdk),
             as.character(SDK_TYPE),
             as.numeric(run),
             as.character("CPU"),
             min(dataRead$CPU),
             mean(dataRead$CPU),
             median(dataRead$CPU),
             max(dataRead$CPU)
             )
  dataByRun = rbindlist(list(dataByRun, row))
}

#######################################################
# Reading of files containing info about memory usage #
#######################################################
file.names <- dir(DATA_FOLDER, pattern ="*.pss")
for(fileIndex in 1:length(file.names))
{
  elements = unlist(strsplit(file.names[fileIndex],"-"))
  sdk = elements[1]
  run = unlist(strsplit(elements[2],".pss"))
  
  tic(msg = "File read!")
  print(paste("-> Reading file '", file.names[fileIndex], "'", sep=""))
  filePath = paste(DATA_FOLDER,file.names[fileIndex], sep="")
  dataRead=fread(filePath, header = F, sep = ' ',select = c("V1"), col.names = c("Memory"))
  dataRead$Memory = as.numeric(dataRead$Memory)
  toc()
  
  row = list(as.character(sdk),
             as.character(SDK_TYPE),
             as.numeric(run),
             as.character("Memory"),
             min(dataRead$Memory),
             mean(dataRead$Memory),
             median(dataRead$Memory),
             max(dataRead$Memory)
  )
  dataByRun = rbindlist(list(dataByRun, row))
}

#Write output dataframe for all the minimal appls (data by run)
write.csv(dataByRun, file = paste(OUTPUT_PATH,"memoryAndCPUByRun.csv",sep=""), row.names = FALSE)
