# This script reads energy traces and generates a CSV file containing the energy consumption of each minimal app and several runs.
# Note that energy traces are generated by the Python script collectEnergyConsumption.py.

require(data.table)
require(doBy)
require(tictoc)

SDK_TYPE = "CrashReporting"
DATA_FOLDER = paste("/Experiments/", SDK_TYPE, "/data/", sep="")
OUTPUT_PATH = paste("/Experiments/", SDK_TYPE, "/results/", sep="")

dataByRun <- data.table("SdkName"=character(),
                        "SdkType"=character(),
                         "Run"=numeric(),
                         "Value"=numeric(),
                         stringsAsFactors=FALSE)

#################################################
# Reading of files containing info about Energy #
#################################################
file.names <- dir(DATA_FOLDER, pattern ="*.energy.zip")
for(fileIndex in 1:length(file.names))
{
  elements = unlist(strsplit(file.names[fileIndex],"-"))
  sdk = elements[1]
  run = as.numeric(unlist(strsplit(elements[2],".energy.zip")))
  
  tic(msg = "File read!")
  print(paste("-> Reading file '", file.names[fileIndex], "'", sep=""))
  filePath = paste(DATA_FOLDER,file.names[fileIndex], sep="")
  dataRead=fread(paste('unzip -cq ', filePath, sep = ""), header = T, sep = ',', select = c("Energy"))
  toc()
  
  row = list(as.character(sdk),
             as.character(SDK_TYPE),
             as.numeric(run),
             sum(dataRead$Energy)
             )
  dataByRun = rbindlist(list(dataByRun, row))
}

#Write output dataframe for all the applications (data by run)
write.csv(dataByRun, file = paste(OUTPUT_PATH,"energyByRun.csv",sep=""), row.names = FALSE)
